# Generated by Django 2.1.5 on 2019-01-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190124_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='product_images',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
