# Generated by Django 2.1.5 on 2019-01-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190125_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='feature1',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='feature3',
        ),
    ]
