# Generated by Django 2.1.5 on 2019-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190125_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='feature_stock',
            field=models.IntegerField(default=100),
        ),
    ]
