# Generated by Django 2.1.5 on 2019-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190125_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
