# Generated by Django 2.1.5 on 2019-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_shoppingcart_order_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('order_completed',)},
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
