# Generated by Django 2.1.5 on 2019-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190126_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_text2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
